version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-bookmark-app"
s3_bucket = "resource-bucket-446502295847-a9e31d90"
s3_prefix = "sam-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "APIGatewayStageName=\"dev\" LambdaDeploymentRole=\"arn:aws:iam::446502295847:role/LambdaDeploymentRole\""



